### ISSUE TITLE
Key Reinstallation Attacks WPA2

### ISSUE THREAD

**Issue by Micha-Btz** [cm12-amami/discussion#6] opened 2017-10-17 08:14 UTC
As described https://www.krackattacks.com/ we should take a look at the LOS patches.

https://review.lineageos.org/#/q/topic:krack-n

**Comment by MSe1969** [comment] 2017-10-17 11:07
definitely - I had planned to open the exact same issue :)

**Comment by MSe1969** [comment] 2017-10-17 11:10
https://review.lineageos.org/#/q/topic:krack-m seems however closer to our code base

**Comment by MSe1969** [comment] 2017-10-17 17:56
Here are the original patches: https://w1.fi/security/2017-1/

**Comment by MSe1969** [comment] 2017-10-17 18:04
https://w1.fi/cgit/hostap/commit/?id=0e3bd7ac684a2289aa613347e2f3ad54ad6a9449
https://w1.fi/cgit/hostap/commit/?id=cb5132bb35698cc0c743e34fe0e845dfc4c3e410
https://w1.fi/cgit/hostap/commit/?id=87e2db16bafcbc60b8d0016175814a73c1e8ed45
https://w1.fi/cgit/hostap/commit/?id=53bb18cc8b7a4da72e47e4b3752d0d2135cffb23
https://w1.fi/cgit/hostap/commit/?id=0adc9b28b39d414d5febfff752f6a1576f785c85
https://w1.fi/cgit/hostap/commit/?id=ff89af96e5a35c86f50330d2b86c18323318a60c
https://w1.fi/cgit/hostap/commit/?id=adae51f8b94d63313a9a922b95a402ad3f182320
https://w1.fi/cgit/hostap/commit/?id=2a9c5217b18be9462a5329626e2f95cc7dd8d4f1

**Comment by MSe1969** [comment] 2017-10-18 11:17
Fork of repo done and applied patches - now doing test build.
Had to backport stuff, so curious whether it works or not - please also have a look and test WiFi and also WiFi tethering

**Comment by MSe1969** [comment] 2017-10-18 15:09
Have successfully tested the build (WiFi and Hotspot). Above commits have been implemented as follows into our fork:
1 cherry-picked from LOS (krack-m topic)
2 cherry-picked from LOS (krack-m topic, with conflict resolution)
3 cherry-picked from LOS (krack-m topic)
4 manual backport
5 cherry-picked from LOS (krack-m topic)
6 manual backport
7 does not apply to our version
8 cherry-picked from LOS (krack-m topic, with conflict resolution)
@Micha-Btz @hahnjo - please test/review also on your end

**Comment by Micha-Btz** [comment] 2017-10-19 09:41
Have build yesterday evening and wlan works like a charm. Tethering I can't test.

**Comment by MSe1969** [comment] 2017-10-19 10:55
I've moved it to our stable branch (main manifest).
As we can't really test whether the vuln. is fixed, I propose to close the issue.
I am currently building a new webview M64 and test it, then I'll ship a build

**Comment by MSe1969** [comment] 2017-10-20 19:59
shipped and announced => closed

**Comment by Micha-Btz** [comment] 2017-10-28 16:32
@MSe1969 
as described here https://forum.xda-developers.com/showpost.php?p=74327512&postcount=294 
for me is WPA with TKIP on my fritzbox not possible. Can you offer with which configuration it works for you?

**Comment by Micha-Btz** [comment] 2017-10-28 16:37
as far as I know you use a cm-13.0 rom how it is there?

**Comment by MSe1969** [comment] 2017-10-28 22:33
Hi,
I have reopened the issue - I can confirm that there is (or better: was) an issue.
I have force-pushed the correction, so before doing "repo sync", make sure to do `git reset --hard HEAD~7` in the **wpa_supplicant_8** repo locally. 
We should leave the issue open, because I would like to implement some further patches. The issue was, that the cherry-pick resolution suggested to take over the missing lines of the "context block" in two cases, which led to resetting variables needed in this lower version.

The current state looks as follows:
I've reset my original 7 commits
implemented https://review.lineageos.org/#/c/193713/ before starting with the patches
1 cherry-picked from LOS (krack-m-alt topic)
2 cherry-picked from LOS (krack-m-alt topic, with fixed conflict resolution)
3 cherry-picked from LOS (krack-m topic)
4 left out (see below)
5 cherry-picked from LOS (krack-m-alt topic)
6 manual backport
7 does not apply to our version
8 cherry-picked from LOS (krack-m-alt topic, with fixed conflict resolution)

As for patch 0004 (Prevent installation of an all-zero TK) - I need to check, whether the manual backport is properly done. Further, I will apply/backport and test some further recommended patches (see krack-m-alt topic at LineageOS, but not all - requires further investigation).

Uploaded new build, further working on it

**Comment by Micha-Btz** [comment] 2017-10-29 16:50
for me it works now also with wpa and tkip. great work

**Comment by MSe1969** [comment] 2017-10-31 11:52
we need to leave out patch 0004 (Prevent installation of an all-zero TK) - it is not applicable for our version, and my attempt to backport it seems to be the root cause for the WPA-TKIP issue. Although the backport looks trivial, there seems to be a dependency somewhere else. Will now work on further recommendations.

**Comment by MSe1969** [comment] 2017-11-05 15:26
I have applied same patches as in topic 'krack-m-alt', but - as previously mentioned - without patches 
 0004 (Prevent installation of an all-zero TK)
 0007 (WNM Ignore WNM Sleep Mode Response without pending request)

Tested sucessfully WPA2, WPA(v1) and AP functionality - issue closed

**Closed as completed by MSe1969** 2017-11-05 15:26 UTC
